In [4]:
import pandas as pd
import joblib as jl
df: pd.DataFrame = jl.load('car_sales_data.pkl')
df

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
0,Male,13500,Ford,Expedition,Auto,Black,26000
1,Male,1480000,Dodge,Durango,Auto,Black,19000
2,Male,1035000,Cadillac,Eldorado,Manual,Red,31500
3,Male,13500,Toyota,Celica,Manual,Pale White,14000
4,Male,1465000,Acura,TL,Auto,Red,24500
...,...,...,...,...,...,...,...
23898,Male,530000,Volvo,C70,Manual,Pale White,24000
23900,Female,771000,Ford,Contour,Auto,Red,19000
23902,Female,900000,Chevrolet,Prizm,Auto,Black,16000
23903,Male,705000,BMW,328i,Manual,Red,21000
23905,Male,1225000,Lexus,ES300,Auto,Pale White,27500

In [17]:
# Getting Data Frame containing only data about Hyundai
df_hyundai = df.query('Company == "Hyundai"')
df_hyundai

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
16,Female,535000,Hyundai,Accent,Manual,Black,18000
124,Female,1690000,Hyundai,Sonata,Manual,Black,15000
168,Male,955000,Hyundai,Elantra,Manual,Pale White,26000
250,Male,457000,Hyundai,Sonata,Manual,Pale White,21000
289,Male,13500,Hyundai,Sonata,Manual,Black,20000
...,...,...,...,...,...,...,...
23248,Female,1675000,Hyundai,Sonata,Manual,Black,20500
23432,Female,13500,Hyundai,Elantra,Manual,Red,22000
23650,Female,460000,Hyundai,Sonata,Manual,Black,15000
23738,Male,705000,Hyundai,Sonata,Manual,Red,21000
23745,Male,681500,Hyundai,Accent,Manual,Black,18500

In [16]:
# Getting Data Frame containing only data about Toyota with price greater than 40000
min_price = 40000
df_filtered = df.query('Company == "Toyota" and `Price ($)` > @min_price')
df_filtered

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
239,Male,1350000,Toyota,Tacoma,Auto,Pale White,53000
258,Male,1151000,Toyota,Corolla,Auto,Pale White,41100
269,Female,825000,Toyota,Tacoma,Manual,Pale White,82000
308,Female,13500,Toyota,Corolla,Auto,Pale White,41000
358,Male,1326000,Toyota,RAV4,Manual,Black,85600
...,...,...,...,...,...,...,...
23379,Male,1300000,Toyota,Celica,Auto,Pale White,45001
23385,Female,615000,Toyota,Tacoma,Auto,Pale White,53000
23443,Male,2400000,Toyota,RAV4,Manual,Black,85000
23476,Male,520000,Toyota,Celica,Auto,Pale White,45000
23735,Male,1635000,Toyota,Tacoma,Auto,Pale White,53501

In [39]:
# Define 3 most popular car's models
models = df['Company'] +' ' + df['Model']
top3 = models.value_counts().head(3)
top3

Chevrolet Prizm          362
Mitsubishi Diamante      347
Oldsmobile Silhouette    337
Name: count, dtype: int64